sudo: false

addons:
    apt_packages:
        - lib32stdc++6  # needed for spcomp

env:
    - SMVERSION=1.9
    - SMVERSION=1.10

before_script:
    # install smbuilder
    - git clone https://github.com/splewis/sm-builder
    - cd sm-builder
    - pip install --user -r requirements.txt
    - python setup.py install --prefix=~/.local
    - cd ..

    # install the sourcemod compiler
    - SMPACKAGE="http://sourcemod.net/latest.php?os=linux&version=${SMVERSION}"
    - wget $SMPACKAGE
    - tar xfz $(basename $SMPACKAGE)
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
    - PATH+=":$PWD"
    - cd include
    - wget https://raw.githubusercontent.com/KyleSanderson/SteamWorks/master/Pawn/includes/SteamWorks.inc
    - git clone https://github.com/clugg/sm-json
    - cp -r sm-json/addons/sourcemod/scripting/include/* .
    - cd ../../../..

script:
    - smbuilder --flags="-E"

after_script:
    - cd ./builds/get5
    - zip -r get5.zip addons/ cfg/ LICENSE README.md
    - curl -F "file=@get5.zip" https://file.io

notifications:
    email: false
